/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package mic.crm.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import mic.crm.common.auditor.AuditorENT;
import mic.crm.common.auditor.AuditorLST;
import mic.crm.common.customer.CustomerLST;
import mic.crm.hibernate.SellDAOManager;
import mic.crm.hibernate.auditor.AuditorDAOInterface;
import mic.crm.hibernate.customer.CustomerDAOInterface;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-21-2012
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="list" path="/pages/auditor/auditorList.jsp"
 */
public class AuditorAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionForward af = null;
		String reqCode = "";
		reqCode = request.getParameter("reqCode");
		if (reqCode==null || reqCode.equalsIgnoreCase("list")){
			AuditorLST auditorLST = new AuditorLST();
			AuditorLST lst = new AuditorLST();
			auditorLST = getDAO().getAuditorLST(lst);
			request.setAttribute("list", auditorLST);
			af = mapping.findForward("list");
		} else if (reqCode.equals("save") || reqCode.equals("edit")){
		AuditorENT auditorENT = new AuditorENT();
		af = mapping.findForward("edit");
		}
		return af;
	}
	
	private static AuditorDAOInterface getDAO (){
		return SellDAOManager.getAuditorDAOInterface();
	}
}
